#!/home/lighthouse/anaconda3/envs/study/bin/python
import pymysql
import pymysql.cursors

conn = pymysql.connect(host='localhost',user='root',passwd='shenwenjie1314',database='blog',charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor)

with conn:
    with conn.cursor() as cursor:
        sql = 'select * from blog_article limit 100'
        cursor.execute(sql)
        result = cursor.fetchall()
        for a in result:
            print(a)
try:
    with conn:
        with conn.cursor() as cursor:
            sql = 'insert into blog_article (id, creator, create_time, updater, update_time, article_name, author, content) values (uuid(),%s,current_date,null,null,uuid(),%s,uuid())'
            cursor.execute(sql,('shen','shen'))
        conn.commit()
except:
    conn.rollback()